name: CI Process

on:
  - push

jobs:
  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v2.3.4
      -
        name: Setup Node Environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
      -
        name: Install node dependencies
        run: npm install -D
      -
        name: Lint CSS
        run: npm run lint:css